job_environments:
  common_environment: &common_environment
    APP_HOSTPATH: turkey
    CONTAINER_PREFIX: planet4-turkey
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: k8s.p4.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GOOGLE_PROJECT_ID: planet-4-151612
    GCLOUD_CLUSTER: p4-development
    HELM_NAMESPACE: develop
    HELM_RELEASE: planet4-turkey
    NEWRELIC_APPNAME: P4 Turkey Development
    WP_DB_NAME: planet4-turkey_wordpress_develop
    WP_STATELESS_BUCKET: planet4-turkey-stateless-develop
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: release.k8s.p4.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: turkey
    HELM_RELEASE: planet4-turkey-release
    NEWRELIC_APPNAME: P4 Turkey Release
    WP_DB_NAME: planet4-turkey_wordpress_release
    WP_STATELESS_BUCKET: planet4-turkey-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: master.k8s.p4.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: turkey
    HELM_RELEASE: planet4-turkey-master
    MIN_REPLICA_COUNT: 2
    NEWRELIC_APPNAME: P4 Turkey Production
    WP_DB_NAME: planet4-turkey_wordpress_master
    WP_STATELESS_BUCKET: planet4-turkey-stateless
